-- Migration 001: AI ingestion fields + patient-protocol signals

-- Add raw extracted data to patient documents
ALTER TABLE patient_documents
    ADD COLUMN IF NOT EXISTS raw_extracted_data TEXT;

-- Add structured criteria JSON to trials (in addition to existing plain text fields)
ALTER TABLE trials
    ADD COLUMN IF NOT EXISTS extracted_criteria_json TEXT;

-- Patient-Protocol eligibility signals (generated by AI matching job)
CREATE TABLE IF NOT EXISTS patient_protocol_signals (
    id TEXT PRIMARY KEY,
    site_id TEXT NOT NULL REFERENCES sites(id),
    patient_id TEXT NOT NULL REFERENCES patients(id),
    trial_id TEXT NOT NULL REFERENCES trials(id),
    overall_status TEXT NOT NULL CHECK (overall_status IN ('LIKELY_ELIGIBLE', 'BORDERLINE', 'LIKELY_INELIGIBLE')),
    confidence TEXT NOT NULL CHECK (confidence IN ('HIGH', 'MEDIUM', 'LOW')),
    criteria_breakdown TEXT DEFAULT '[]',
    summary TEXT,
    missing_data TEXT DEFAULT '[]',
    auto_assigned BOOLEAN NOT NULL DEFAULT FALSE,
    assigned_at TIMESTAMPTZ,
    last_evaluated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(patient_id, trial_id)
);

CREATE INDEX IF NOT EXISTS idx_pps_patient ON patient_protocol_signals(patient_id);
CREATE INDEX IF NOT EXISTS idx_pps_trial ON patient_protocol_signals(trial_id);
CREATE INDEX IF NOT EXISTS idx_pps_site_status ON patient_protocol_signals(site_id, overall_status);
